name: logger
description: Small, easy to use and extensible logger which prints beautiful logs.
version: 0.9.4
homepage: https://github.com/leisim/logger

environment:
  sdk: '>=2.8.1 <3.0.0'

dev_dependencies:
  test: ^1.15.4
  pedantic: ^1.9.0
